#include "ws2811.h"
#include "config.h"
#include "ws2811.pio.h"   // generated by pioasm during build

#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/clocks.h"
#include "pico/stdlib.h"
#include <string.h>

#define MAX_OUTPUTS     8
#define WORDS_PER_UNI   LEDS_PER_UNIVERSE  // one uint32_t per pixel

// ── pixel buffers ─────────────────────────────────────────────────────────────
// Two sets: one being sent via DMA, one being written by the ArtNet callback.
static uint32_t _buf[2][MAX_OUTPUTS][WORDS_PER_UNI];
static volatile uint _active = 0;  // index of the buffer currently in DMA

// ── PIO / DMA handles ─────────────────────────────────────────────────────────
static PIO  _pio[MAX_OUTPUTS];
static uint _sm [MAX_OUTPUTS];
static int  _dma[MAX_OUTPUTS];
static uint _num_outputs;

// ── helpers ───────────────────────────────────────────────────────────────────
static inline uint32_t rgb_to_word(uint8_t r, uint8_t g, uint8_t b)
{
#if WS2811_COLOR_RGB
    return ((uint32_t)r << 24) | ((uint32_t)g << 16) | ((uint32_t)b << 8);
#else   // GRB (WS2812)
    return ((uint32_t)g << 24) | ((uint32_t)r << 16) | ((uint32_t)b << 8);
#endif
}

// ── public API ────────────────────────────────────────────────────────────────

void ws2811_init(uint num_outputs, uint base_pin)
{
    _num_outputs = (num_outputs > MAX_OUTPUTS) ? MAX_OUTPUTS : num_outputs;

    // RP2350 has two PIO blocks with 4 state machines each → 8 total.
    // Distribute outputs across both PIO blocks.
    uint offset0 = pio_add_program(pio0, &ws2811_program);
    uint offset1 = pio_add_program(pio1, &ws2811_program);

    for (uint i = 0; i < _num_outputs; i++) {
        PIO pio  = (i < 4) ? pio0 : pio1;
        uint sm  = i % 4;
        uint offset = (i < 4) ? offset0 : offset1;

        _pio[i] = pio;
        _sm[i]  = sm;

        ws2811_program_init(pio, sm, offset, base_pin + i);

        // Claim a DMA channel for this output
        _dma[i] = dma_claim_unused_channel(true);

        dma_channel_config cfg = dma_channel_get_default_config(_dma[i]);
        channel_config_set_transfer_data_size(&cfg, DMA_SIZE_32);
        channel_config_set_read_increment(&cfg, true);
        channel_config_set_write_increment(&cfg, false);
        channel_config_set_dreq(&cfg, pio_get_dreq(pio, sm, true));

        dma_channel_configure(
            _dma[i], &cfg,
            &pio->txf[sm],                  // write to PIO TX FIFO
            _buf[0][i],                     // initial read address
            WORDS_PER_UNI,
            false                           // don't start yet
        );
    }

    // Clear both buffers (all LEDs off)
    memset(_buf, 0, sizeof(_buf));
}

void ws2811_update(uint universe, const uint8_t *dmx, uint dmx_len)
{
    if (universe >= _num_outputs) return;

    // Write into the inactive buffer
    uint inactive = _active ^ 1;
    uint32_t *dst = _buf[inactive][universe];

    uint pixels = dmx_len / 3;
    if (pixels > LEDS_PER_UNIVERSE) pixels = LEDS_PER_UNIVERSE;

    for (uint i = 0; i < pixels; i++) {
        dst[i] = rgb_to_word(dmx[i * 3], dmx[i * 3 + 1], dmx[i * 3 + 2]);
    }
    // Pad remaining pixels with black if DMX data is short
    for (uint i = pixels; i < LEDS_PER_UNIVERSE; i++) {
        dst[i] = 0;
    }
}

void ws2811_wait(void)
{
    for (uint i = 0; i < _num_outputs; i++) {
        dma_channel_wait_for_finish_blocking(_dma[i]);
    }
}

void ws2811_send_all(void)
{
    ws2811_wait();  // ensure previous transfers done

    // Swap to the buffer that was just written by ws2811_update
    _active ^= 1;

    for (uint i = 0; i < _num_outputs; i++) {
        dma_channel_set_read_addr(_dma[i], _buf[_active][i], true);
    }
}
